package main

import (
	"bytes"
	"encoding/binary"
	"flag"
	"fmt"
	"image/png"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	asdexAssetPackage   = "assets"
	asdexRendererImport = "github.com/juliusplatzer/reds/renderer"

	asdexFontVarName  = "AsdexFonts"
	asdexFontFuncName = "AsdexFont"

	asdexCursorVarName  = "AsdexCursors"
	asdexCursorFuncName = "AsdexCursor"
)

var asdexWantedFontSizes = map[int32]bool{
	1: true,
	2: true,
	3: true,
	4: true,
	5: true,
	6: true,
}

var pngSignature = []byte{0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n'}

type cursorBitmap struct {
	name    string
	width   int
	height  int
	hotspot [2]int
	pixels  []uint32 // row-major 0xRRGGBBAA
}

type iconDirEntry struct {
	width      int
	height     int
	hotspotX   int
	hotspotY   int
	bytesInRes uint32
	imageOff   uint32
}

func runAsdex(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: crc2reds asdex <font|cursors> ...")
	}

	switch args[0] {
	case "font":
		return runAsdexFont(args[1:])
	case "cursors":
		return runAsdexCursors(args[1:])
	default:
		return fmt.Errorf("unknown ASDE-X conversion %q; expected font or cursors", args[0])
	}
}

func runAsdexFont(args []string) error {
	fs := flag.NewFlagSet("asdex font", flag.ContinueOnError)

	inPath := fs.String("in", "", "input ASDE-X .bin or .bin.zst font file")
	outPath := fs.String("out", "", "output generated Go file")

	if err := fs.Parse(args); err != nil {
		return err
	}
	if *inPath == "" || *outPath == "" {
		return fmt.Errorf("usage: crc2reds asdex font -in /path/to/font.bin.zst -out asdex/assets/font.go")
	}

	return convertAsdexFont(*inPath, *outPath)
}

func convertAsdexFont(inPath, outPath string) error {
	info, err := os.Stat(inPath)
	if err != nil {
		return err
	}
	if info.IsDir() {
		return fmt.Errorf("-in must be an ASDE-X .bin or .bin.zst font file: %s", inPath)
	}
	if !isBinInputFile(filepath.Base(inPath)) {
		return fmt.Errorf("-in must be an ASDE-X .bin or .bin.zst font file: %s", inPath)
	}

	raw, err := readMaybeZstd(inPath)
	if err != nil {
		return err
	}

	sizes, err := parseLegacyFont("", raw)
	if err != nil {
		return err
	}

	filtered := sizes[:0]
	for _, fs := range sizes {
		if asdexWantedFontSizes[fs.size] {
			filtered = append(filtered, fs)
		}
	}
	if len(filtered) == 0 {
		return fmt.Errorf("no sizes 1..6 found in %s", inPath)
	}

	if err := writeAsdexFontGo(outPath, filtered); err != nil {
		return err
	}

	fmt.Printf("wrote %s\n", outPath)
	fmt.Printf("converted sizes:")
	for _, fs := range filtered {
		fmt.Printf(" %d", fs.size)
	}
	fmt.Println()

	return nil
}

func writeAsdexFontGo(outPath string, sizes []legacyFontSize) error {
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}

	var b strings.Builder

	b.WriteString("// Code generated by cmd/crc2reds; DO NOT EDIT.\n")
	b.WriteString("// Source: CRC's ASDE-X font.bin.zst converted to grayscale glyph data.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", asdexAssetPackage)
	fmt.Fprintf(&b, "import renderer %q\n\n", asdexRendererImport)

	fmt.Fprintf(&b, "var %s = map[int]*renderer.AlphaBitmapFont{\n", asdexFontVarName)

	for _, fs := range sizes {
		fmt.Fprintf(&b, "\t%d: {\n", fs.size)
		fmt.Fprintf(&b, "\t\tPointSize: %d,\n", fs.size)
		fmt.Fprintf(&b, "\t\tWidth:     %d,\n", nominalWidth(fs))
		fmt.Fprintf(&b, "\t\tHeight:    %d,\n", fs.lineHeight)
		b.WriteString("\t\tGlyphs: []renderer.AlphaBitmapGlyph{\n")

		for _, g := range fs.glyphs {
			alpha := extractAsdexAlpha(fs, g)
			offsetX := g.bearingX
			offsetY := fs.lineHeight - g.bearingY

			fmt.Fprintf(&b, "\t\t\t%d: {\n", g.codepoint)
			fmt.Fprintf(&b, "\t\t\t\tName:   %q,\n", fmt.Sprintf("char%d", g.codepoint))
			fmt.Fprintf(&b, "\t\t\t\tStepX:  %d,\n", g.advance)
			fmt.Fprintf(&b, "\t\t\t\tBounds: [2]int{%d, %d},\n", g.width, g.height)
			fmt.Fprintf(&b, "\t\t\t\tOffset: [2]int{%d, %d},\n", offsetX, offsetY)
			fmt.Fprintf(&b, "\t\t\t\tAlpha:  %s,\n", formatUint8Array(alpha, "\t\t\t\t"))
			b.WriteString("\t\t\t},\n")
		}

		b.WriteString("\t\t},\n")
		b.WriteString("\t},\n\n")
	}

	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "func %s(size int) (*renderer.AlphaBitmapFont, bool) {\n", asdexFontFuncName)
	fmt.Fprintf(&b, "\tf, ok := %s[size]\n", asdexFontVarName)
	b.WriteString("\treturn f, ok\n")
	b.WriteString("}\n")

	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}

func extractAsdexAlpha(fs legacyFontSize, glyph legacyGlyph) []byte {
	if glyph.width <= 0 || glyph.height <= 0 {
		return nil
	}

	w := int(glyph.width)
	h := int(glyph.height)
	atlasWidth := int(fs.atlasWidth)
	x0 := int(glyph.textureOffset)

	out := make([]byte, 0, w*h)
	for y := 0; y < h; y++ {
		rowStart := y*atlasWidth + x0
		out = append(out, fs.atlasR8[rowStart:rowStart+w]...)
	}
	return out
}

func formatUint8Array(values []byte, indent string) string {
	if len(values) == 0 {
		return "nil"
	}

	const perLine = 24

	var b strings.Builder
	b.WriteString("[]uint8{")
	for i := 0; i < len(values); i += perLine {
		end := i + perLine
		if end > len(values) {
			end = len(values)
		}

		b.WriteString("\n")
		b.WriteString(indent)
		for j := i; j < end; j++ {
			if j > i {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%d", values[j])
		}
		b.WriteString(",")
	}
	b.WriteString("\n")
	b.WriteString(indent[:len(indent)-1])
	b.WriteString("}")

	return b.String()
}

func runAsdexCursors(args []string) error {
	fs := flag.NewFlagSet("asdex cursors", flag.ContinueOnError)

	inPath := fs.String("in", "", "input ASDE-X .cur/.cur.zst file or directory containing cursor files")
	outPath := fs.String("out", "", "output generated Go file")

	if err := fs.Parse(args); err != nil {
		return err
	}
	if *inPath == "" || *outPath == "" {
		return fmt.Errorf("usage: crc2reds asdex cursors -in /path/to/cursors-or-cursor.cur.zst -out asdex/assets/cursors.go")
	}

	return convertAsdexCursors(*inPath, *outPath)
}

func convertAsdexCursors(inPath, outPath string) error {
	paths, err := cursorInputFiles(inPath)
	if err != nil {
		return err
	}
	if len(paths) == 0 {
		return fmt.Errorf("no .cur or .cur.zst files found in %s", inPath)
	}

	cursors := make([]cursorBitmap, 0, len(paths))
	seen := make(map[string]bool, len(paths))

	for _, path := range paths {
		cursor, err := decodeCursorFile(path)
		if err != nil {
			return err
		}
		if seen[cursor.name] {
			return fmt.Errorf("duplicate cursor name after sanitizing: %s", cursor.name)
		}
		seen[cursor.name] = true
		cursors = append(cursors, cursor)
	}

	sort.Slice(cursors, func(i, j int) bool {
		return cursors[i].name < cursors[j].name
	})

	if err := writeAsdexCursorGo(outPath, cursors); err != nil {
		return err
	}

	fmt.Printf("wrote %s\n", outPath)
	fmt.Print("converted cursors:")
	for _, cursor := range cursors {
		fmt.Printf(" %s(%dx%d hot=%d,%d)", cursor.name, cursor.width, cursor.height, cursor.hotspot[0], cursor.hotspot[1])
	}
	fmt.Println()

	return nil
}

func cursorInputFiles(inPath string) ([]string, error) {
	info, err := os.Stat(inPath)
	if err != nil {
		return nil, err
	}

	if !info.IsDir() {
		if !isCursorInputFile(filepath.Base(inPath)) {
			return nil, fmt.Errorf("-in must be an ASDE-X .cur/.cur.zst file or a directory containing cursor files: %s", inPath)
		}
		return []string{inPath}, nil
	}

	entries, err := os.ReadDir(inPath)
	if err != nil {
		return nil, err
	}

	var paths []string
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		name := entry.Name()
		if strings.HasPrefix(name, "._") {
			continue
		}
		if isCursorInputFile(name) {
			paths = append(paths, filepath.Join(inPath, name))
		}
	}

	sort.Strings(paths)
	return paths, nil
}

func isBinInputFile(name string) bool {
	return strings.HasSuffix(name, ".bin") || strings.HasSuffix(name, ".bin.zst")
}

func isCursorInputFile(name string) bool {
	return strings.HasSuffix(name, ".cur") || strings.HasSuffix(name, ".cur.zst")
}

func decodeCursorFile(path string) (cursorBitmap, error) {
	raw, err := readMaybeZstd(path)
	if err != nil {
		return cursorBitmap{}, err
	}

	if len(raw) < 6 {
		return cursorBitmap{}, fmt.Errorf("%s: too short for CUR header", path)
	}

	reserved := binary.LittleEndian.Uint16(raw[0:2])
	typ := binary.LittleEndian.Uint16(raw[2:4])
	count := binary.LittleEndian.Uint16(raw[4:6])

	if reserved != 0 || typ != 2 {
		return cursorBitmap{}, fmt.Errorf("%s: not a Windows .cur file: reserved=%d type=%d", path, reserved, typ)
	}
	if count == 0 {
		return cursorBitmap{}, fmt.Errorf("%s: no cursor images", path)
	}

	entries := make([]iconDirEntry, 0, count)
	off := 6
	for i := 0; i < int(count); i++ {
		if off+16 > len(raw) {
			return cursorBitmap{}, fmt.Errorf("%s: truncated cursor directory", path)
		}

		width := int(raw[off])
		height := int(raw[off+1])
		if width == 0 {
			width = 256
		}
		if height == 0 {
			height = 256
		}

		entry := iconDirEntry{
			width:      width,
			height:     height,
			hotspotX:   int(binary.LittleEndian.Uint16(raw[off+4 : off+6])),
			hotspotY:   int(binary.LittleEndian.Uint16(raw[off+6 : off+8])),
			bytesInRes: binary.LittleEndian.Uint32(raw[off+8 : off+12]),
			imageOff:   binary.LittleEndian.Uint32(raw[off+12 : off+16]),
		}
		entries = append(entries, entry)
		off += 16
	}

	sort.Slice(entries, func(i, j int) bool {
		areaI := entries[i].width * entries[i].height
		areaJ := entries[j].width * entries[j].height
		if areaI != areaJ {
			return areaI > areaJ
		}
		return entries[i].bytesInRes > entries[j].bytesInRes
	})

	name := cursorNameFromPath(path)
	cursor, err := decodeCursorImage(raw, entries[0], name)
	if err != nil {
		return cursorBitmap{}, fmt.Errorf("%s: %w", path, err)
	}
	return cursor, nil
}

func decodeCursorImage(file []byte, entry iconDirEntry, name string) (cursorBitmap, error) {
	start := int(entry.imageOff)
	end := start + int(entry.bytesInRes)

	if start < 0 || end < start || end > len(file) {
		return cursorBitmap{}, fmt.Errorf("cursor image outside file")
	}

	payload := file[start:end]
	if len(payload) >= len(pngSignature) && bytes.Equal(payload[:len(pngSignature)], pngSignature) {
		return decodePNGCursor(payload, entry.hotspotX, entry.hotspotY, name)
	}

	return decodeDIBCursor(payload, entry.hotspotX, entry.hotspotY, name)
}

func decodePNGCursor(payload []byte, hotX, hotY int, name string) (cursorBitmap, error) {
	img, err := png.Decode(bytes.NewReader(payload))
	if err != nil {
		return cursorBitmap{}, fmt.Errorf("decode PNG cursor: %w", err)
	}

	bounds := img.Bounds()
	width := bounds.Dx()
	height := bounds.Dy()

	pixels := make([]uint32, 0, width*height)
	for y := bounds.Min.Y; y < bounds.Max.Y; y++ {
		for x := bounds.Min.X; x < bounds.Max.X; x++ {
			r16, g16, b16, a16 := img.At(x, y).RGBA()
			pixels = append(pixels, rgba(uint8(r16>>8), uint8(g16>>8), uint8(b16>>8), uint8(a16>>8)))
		}
	}

	return cursorBitmap{
		name:    name,
		width:   width,
		height:  height,
		hotspot: [2]int{hotX, hotY},
		pixels:  pixels,
	}, nil
}

func decodeDIBCursor(payload []byte, hotX, hotY int, name string) (cursorBitmap, error) {
	if len(payload) < 40 {
		return cursorBitmap{}, fmt.Errorf("truncated BITMAPINFOHEADER")
	}

	headerSize := int(int32(binary.LittleEndian.Uint32(payload[0:4])))
	if headerSize < 40 {
		return cursorBitmap{}, fmt.Errorf("unsupported DIB header size %d", headerSize)
	}
	if headerSize > len(payload) {
		return cursorBitmap{}, fmt.Errorf("truncated DIB header")
	}

	width := int(int32(binary.LittleEndian.Uint32(payload[4:8])))
	dibHeight := int(int32(binary.LittleEndian.Uint32(payload[8:12])))
	planes := binary.LittleEndian.Uint16(payload[12:14])
	bpp := int(binary.LittleEndian.Uint16(payload[14:16]))
	compression := binary.LittleEndian.Uint32(payload[16:20])
	clrUsed := int(binary.LittleEndian.Uint32(payload[32:36]))

	if width <= 0 || dibHeight == 0 {
		return cursorBitmap{}, fmt.Errorf("invalid DIB dimensions %dx%d", width, dibHeight)
	}
	if planes != 1 {
		return cursorBitmap{}, fmt.Errorf("expected one plane, got %d", planes)
	}
	if compression != 0 {
		return cursorBitmap{}, fmt.Errorf("compressed DIB cursors are not supported, compression=%d", compression)
	}

	height := abs(dibHeight) / 2
	topDown := dibHeight < 0
	if height <= 0 {
		return cursorBitmap{}, fmt.Errorf("invalid cursor bitmap height %d", dibHeight)
	}

	pos := headerSize

	var palette [][4]uint8
	if bpp <= 8 {
		ncolors := clrUsed
		if ncolors == 0 {
			ncolors = 1 << bpp
		}
		if pos+ncolors*4 > len(payload) {
			return cursorBitmap{}, fmt.Errorf("truncated palette")
		}

		palette = make([][4]uint8, ncolors)
		for i := 0; i < ncolors; i++ {
			b := payload[pos+i*4+0]
			g := payload[pos+i*4+1]
			r := payload[pos+i*4+2]
			palette[i] = [4]uint8{r, g, b, 255}
		}
		pos += ncolors * 4
	}

	xorStride := dibStride(width, bpp)
	andStride := dibStride(width, 1)
	xorBytes := xorStride * height
	andBytes := andStride * height

	if pos+xorBytes+andBytes > len(payload) {
		return cursorBitmap{}, fmt.Errorf("truncated bitmap data")
	}

	xorStart := pos
	andStart := pos + xorBytes

	pixels := make([]uint32, width*height)
	hasRealAlpha := false

	for y := 0; y < height; y++ {
		srcY := height - 1 - y
		if topDown {
			srcY = y
		}

		xorRow := payload[xorStart+srcY*xorStride : xorStart+(srcY+1)*xorStride]

		for x := 0; x < width; x++ {
			var r, g, b, a uint8

			switch bpp {
			case 32:
				i := x * 4
				b, g, r, a = xorRow[i], xorRow[i+1], xorRow[i+2], xorRow[i+3]
				if a != 0 {
					hasRealAlpha = true
				}
			case 24:
				i := x * 3
				b, g, r = xorRow[i], xorRow[i+1], xorRow[i+2]
				a = 255
			case 8, 4, 1:
				idx := decodeIndexedPixel(xorRow, x, bpp)
				if idx < len(palette) {
					r, g, b, a = palette[idx][0], palette[idx][1], palette[idx][2], palette[idx][3]
				} else {
					r, g, b, a = 0, 0, 0, 255
				}
			default:
				return cursorBitmap{}, fmt.Errorf("unsupported bits-per-pixel value %d", bpp)
			}

			pixels[y*width+x] = rgba(r, g, b, a)
		}
	}

	for y := 0; y < height; y++ {
		srcY := height - 1 - y
		if topDown {
			srcY = y
		}

		andRow := payload[andStart+srcY*andStride : andStart+(srcY+1)*andStride]

		for x := 0; x < width; x++ {
			px := pixels[y*width+x]
			a := uint8(px & 0xff)

			if bpp == 32 && !hasRealAlpha {
				a = 255
			} else if bpp != 32 {
				a = 255
			}

			if maskBit(andRow, x) != 0 {
				a = 0
			}

			pixels[y*width+x] = (px & 0xffffff00) | uint32(a)
		}
	}

	return cursorBitmap{
		name:    name,
		width:   width,
		height:  height,
		hotspot: [2]int{hotX, hotY},
		pixels:  pixels,
	}, nil
}

func dibStride(width, bitsPerPixel int) int {
	return ((width*bitsPerPixel + 31) / 32) * 4
}

func decodeIndexedPixel(row []byte, x int, bpp int) int {
	switch bpp {
	case 8:
		return int(row[x])
	case 4:
		v := row[x/2]
		if x%2 == 0 {
			return int(v >> 4)
		}
		return int(v & 0x0f)
	case 1:
		return maskBit(row, x)
	default:
		panic("unsupported indexed bpp")
	}
}

func maskBit(row []byte, x int) int {
	v := row[x/8]
	shift := 7 - (x % 8)
	return int((v >> shift) & 1)
}

func rgba(r, g, b, a uint8) uint32 {
	return uint32(r)<<24 | uint32(g)<<16 | uint32(b)<<8 | uint32(a)
}

func cursorNameFromPath(path string) string {
	base := filepath.Base(path)
	if strings.HasSuffix(base, ".cur.zst") {
		base = strings.TrimSuffix(base, ".cur.zst")
	} else if strings.HasSuffix(base, ".cur") {
		base = strings.TrimSuffix(base, ".cur")
	}

	name := sanitizeIdent(base)
	if name == "Font" {
		return "Cursor"
	}
	return name
}

func writeAsdexCursorGo(outPath string, cursors []cursorBitmap) error {
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by cmd/crc2reds; DO NOT EDIT.\n")
	b.WriteString("// Source: ASDE-X .cur(.zst) files converted to exact RGBA cursor pixels.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", asdexAssetPackage)
	fmt.Fprintf(&b, "import renderer %q\n\n", asdexRendererImport)

	fmt.Fprintf(&b, "var %s = map[string]*renderer.CursorBitmap{\n", asdexCursorVarName)

	for _, cursor := range cursors {
		fmt.Fprintf(&b, "\t%q: {\n", cursor.name)
		fmt.Fprintf(&b, "\t\tName:    %q,\n", cursor.name)
		fmt.Fprintf(&b, "\t\tWidth:   %d,\n", cursor.width)
		fmt.Fprintf(&b, "\t\tHeight:  %d,\n", cursor.height)
		fmt.Fprintf(&b, "\t\tHotspot: [2]int{%d, %d},\n", cursor.hotspot[0], cursor.hotspot[1])
		fmt.Fprintf(&b, "\t\tPixels:  %s,\n", formatUint32Array(cursor.pixels, "\t\t"))
		b.WriteString("\t},\n\n")
	}

	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "func %s(name string) (*renderer.CursorBitmap, bool) {\n", asdexCursorFuncName)
	fmt.Fprintf(&b, "\tc, ok := %s[name]\n", asdexCursorVarName)
	b.WriteString("\treturn c, ok\n")
	b.WriteString("}\n")

	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}
