package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	eramAssetPackage   = "assets"
	eramRendererImport = "github.com/juliusplatzer/reds/renderer"
	eramAllFontsVar    = "EramFonts"

	eramCursorVarName  = "EramCursors"
	eramCursorFuncName = "EramCursor"
)

type eramFamilyFonts struct {
	family string
	sizes  []legacyFontSize
}

func runEram(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: crc2reds eram <font|cursors|maps> ...")
	}

	switch args[0] {
	case "font":
		return runEramFont(args[1:])
	case "cursors":
		return runEramCursors(args[1:])
	case "maps":
		return runEramMaps(args[1:])
	default:
		return fmt.Errorf("unknown ERAM conversion %q; expected font, cursors, or maps", args[0])
	}
}

func runEramFont(args []string) error {
	fs := flag.NewFlagSet("eram font", flag.ContinueOnError)

	inPath := fs.String("in", "", "input ERAM .bin/.bin.zst font file or directory containing font files")
	outPath := fs.String("out", "", "output generated Go file")

	if err := fs.Parse(args); err != nil {
		return err
	}
	if *inPath == "" || *outPath == "" {
		return fmt.Errorf("usage: crc2reds eram font -in /path/to/eram-fonts-or-font.bin.zst -out eram/assets/font.go")
	}

	return convertEramFont(*inPath, *outPath)
}

func convertEramFont(inPath, outPath string) error {
	families, err := parseEramInputPath(inPath)
	if err != nil {
		return err
	}
	if len(families) == 0 {
		return fmt.Errorf("no .bin or .bin.zst font files found in %s", inPath)
	}

	if err := writeEramFontGo(outPath, families); err != nil {
		return err
	}

	fmt.Printf("wrote %s\n", outPath)
	fmt.Print("converted font families:")
	for _, family := range families {
		fmt.Printf(" %s(", family.family)
		for i, size := range family.sizes {
			if i > 0 {
				fmt.Print(",")
			}
			fmt.Print(size.size)
		}
		fmt.Print(")")
	}
	fmt.Println()

	return nil
}

func parseEramInputPath(inPath string) ([]eramFamilyFonts, error) {
	paths, err := eramInputFiles(inPath)
	if err != nil {
		return nil, err
	}

	families := make([]eramFamilyFonts, 0, len(paths))
	for _, path := range paths {
		raw, err := readMaybeZstd(path)
		if err != nil {
			return nil, err
		}

		family := fontFamilyFromPath(path)
		sizes, err := parseLegacyFont(family, raw)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		if err := validateEramFontSizes(sizes); err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}

		families = append(families, eramFamilyFonts{
			family: family,
			sizes:  sizes,
		})
	}

	sort.Slice(families, func(i, j int) bool {
		return families[i].family < families[j].family
	})
	return families, nil
}

func eramInputFiles(inPath string) ([]string, error) {
	info, err := os.Stat(inPath)
	if err != nil {
		return nil, err
	}
	if !info.IsDir() {
		if !isBinInputFile(filepath.Base(inPath)) {
			return nil, fmt.Errorf("-in must be an ERAM .bin/.bin.zst font file or a directory containing font files: %s", inPath)
		}
		return []string{inPath}, nil
	}

	entries, err := os.ReadDir(inPath)
	if err != nil {
		return nil, err
	}

	var paths []string
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasPrefix(name, "._") {
			continue
		}
		if isBinInputFile(name) {
			paths = append(paths, filepath.Join(inPath, name))
		}
	}
	sort.Strings(paths)
	return paths, nil
}

func validateEramFontSizes(sizes []legacyFontSize) error {
	for _, fs := range sizes {
		if !atlasIsBinary(fs.atlasR8) {
			return fmt.Errorf("font %s size %d is not binary 0/255; use alpha conversion instead", fs.family, fs.size)
		}

		for _, glyph := range fs.glyphs {
			if glyph.width > 32 {
				return fmt.Errorf("glyph too wide for VICE-style uint32 rows in size %d, codepoint %d: width=%d",
					fs.size, glyph.codepoint, glyph.width)
			}
		}
	}
	return nil
}

func writeEramFontGo(outPath string, families []eramFamilyFonts) error {
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by cmd/crc2reds; DO NOT EDIT.\n")
	b.WriteString("// Source: ERAM binary .bin(.zst) fonts converted to VICE-style 1-bit glyph rows.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", eramAssetPackage)
	fmt.Fprintf(&b, "import renderer %q\n\n", eramRendererImport)

	fmt.Fprintf(&b, "var %s = map[string]*renderer.MonoBitmapFont{\n", eramAllFontsVar)

	for _, family := range families {
		for _, fs := range family.sizes {
			writeEramFontLiteral(&b, fs)
		}
	}

	b.WriteString("}\n\n")

	for _, family := range families {
		varName := exportedFamilyVarName(family.family)
		fmt.Fprintf(&b, "var %s = map[int]*renderer.MonoBitmapFont{\n", varName)
		for _, fs := range family.sizes {
			fmt.Fprintf(&b, "\t%d: %s[%q],\n", fs.size, eramAllFontsVar, fontKey(fs))
		}
		b.WriteString("}\n\n")
	}

	for _, family := range families {
		funcName := exportedFamilyFuncName(family.family)
		varName := exportedFamilyVarName(family.family)
		fmt.Fprintf(&b, "func %s(size int) (*renderer.MonoBitmapFont, bool) {\n", funcName)
		fmt.Fprintf(&b, "\tf, ok := %s[size]\n", varName)
		b.WriteString("\treturn f, ok\n")
		b.WriteString("}\n\n")
	}

	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}

func writeEramFontLiteral(b *strings.Builder, fs legacyFontSize) {
	fmt.Fprintf(b, "\t%q: {\n", fontKey(fs))
	fmt.Fprintf(b, "\t\tPointSize: %d,\n", fs.size)
	fmt.Fprintf(b, "\t\tWidth:     %d,\n", nominalWidth(fs))
	fmt.Fprintf(b, "\t\tHeight:    %d,\n", fs.lineHeight)
	b.WriteString("\t\tGlyphs: []renderer.MonoBitmapGlyph{\n")

	for _, glyph := range fs.glyphs {
		bitmapRows := glyphBitmapRows(fs, glyph)
		offsetX := glyph.bearingX
		offsetY := fs.lineHeight - glyph.bearingY

		fmt.Fprintf(b, "\t\t\t%d: {\n", glyph.codepoint)
		fmt.Fprintf(b, "\t\t\t\tName:   %q,\n", glyphName(glyph.codepoint))
		fmt.Fprintf(b, "\t\t\t\tStepX:  %d,\n", glyph.advance)
		fmt.Fprintf(b, "\t\t\t\tBounds: [2]int{%d, %d},\n", glyph.width, glyph.height)
		fmt.Fprintf(b, "\t\t\t\tOffset: [2]int{%d, %d},\n", offsetX, offsetY)
		fmt.Fprintf(b, "\t\t\t\tBitmap: %s,\n", formatUint32Array(bitmapRows, "\t\t\t\t"))
		b.WriteString("\t\t\t},\n")
	}

	b.WriteString("\t\t},\n")
	b.WriteString("\t},\n\n")
}

func fontKey(fs legacyFontSize) string {
	return fmt.Sprintf("%s-%d", fs.family, fs.size)
}

func fontFamilyFromPath(path string) string {
	base := filepath.Base(path)
	base = strings.TrimSuffix(base, ".zst")
	base = strings.TrimSuffix(base, ".bin")
	return sanitizeIdent(base)
}

func exportedFamilyVarName(family string) string {
	return sanitizeIdent(family) + "Fonts"
}

func exportedFamilyFuncName(family string) string {
	return sanitizeIdent(family) + "Font"
}

type crcARTCC struct {
	Facility struct {
		ID string `json:"id"`

		ERAMConfiguration struct {
			GeoMaps []crcERAMGeoMap `json:"geoMaps"`
		} `json:"eramConfiguration"`
	} `json:"facility"`

	VideoMaps []crcVideoMap `json:"videoMaps"`
}

type crcERAMGeoMap struct {
	Name       string `json:"name"`
	LabelLine1 string `json:"labelLine1"`
	LabelLine2 string `json:"labelLine2"`

	FilterMenu []struct {
		LabelLine1 string `json:"labelLine1"`
		LabelLine2 string `json:"labelLine2"`
	} `json:"filterMenu"`

	BCGMenu     []string `json:"bcgMenu"`
	VideoMapIDs []string `json:"videoMapIds"`
}

type crcVideoMap struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	TDMOnly bool   `json:"tdmOnly"`
}

type redsERAMMapPackage struct {
	ARTCC     string             `json:"artcc"`
	GeoMaps   []redsERAMGeoMap   `json:"geoMaps"`
	VideoMaps []redsERAMVideoMap `json:"videoMaps"`
}

type redsERAMGeoMap struct {
	Name        string          `json:"name"`
	LabelLine1  string          `json:"labelLine1"`
	LabelLine2  string          `json:"labelLine2"`
	FilterMenu  []redsMapFilter `json:"filterMenu"`
	BCGMenu     []string        `json:"bcgMenu"`
	VideoMapIDs []string        `json:"videoMapIds"`
}

type redsMapFilter struct {
	LabelLine1 string `json:"labelLine1"`
	LabelLine2 string `json:"labelLine2"`
}

type redsERAMVideoMap struct {
	ID      string          `json:"id"`
	Name    string          `json:"name"`
	TDMOnly bool            `json:"tdmOnly,omitempty"`
	GeoJSON json.RawMessage `json:"geojson"`
}

func runEramMaps(args []string) error {
	fs := flag.NewFlagSet("eram maps", flag.ContinueOnError)

	inPath := fs.String("in", "", "CRC data root containing ARTCCs/ and VideoMaps/")
	artcc := fs.String("artcc", "", "ARTCC identifier, e.g. ZLA")
	outPath := fs.String("out", "", "output .json.zst file")

	if err := fs.Parse(args); err != nil {
		return err
	}
	if *inPath == "" || *artcc == "" || *outPath == "" {
		return fmt.Errorf("usage: crc2reds eram maps -in /path/to/CRC -artcc ZLA -out resources/videomaps/eram/ZLA.json.zst")
	}

	return convertEramMaps(*inPath, strings.ToUpper(strings.TrimSpace(*artcc)), *outPath)
}

func convertEramMaps(root, artcc, outPath string) error {
	if artcc == "" {
		return fmt.Errorf("empty ARTCC")
	}

	artccPath := filepath.Join(root, "ARTCCs", artcc+".json")
	raw, err := os.ReadFile(artccPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", artccPath, err)
	}

	var src crcARTCC
	if err := json.Unmarshal(raw, &src); err != nil {
		return fmt.Errorf("decode %s: %w", artccPath, err)
	}

	dst, err := buildRedsERAMMapPackage(root, artcc, src)
	if err != nil {
		return err
	}

	encoded, err := json.Marshal(dst)
	if err != nil {
		return fmt.Errorf("encode ERAM maps: %w", err)
	}

	if err := writeZstd(outPath, encoded); err != nil {
		return err
	}

	fmt.Printf(
		"wrote %s: %d GeoMap groups, %d source videomaps\n",
		outPath,
		len(dst.GeoMaps),
		len(dst.VideoMaps),
	)

	return nil
}

func buildRedsERAMMapPackage(root, artcc string, src crcARTCC) (redsERAMMapPackage, error) {
	dst := redsERAMMapPackage{
		ARTCC: artcc,
	}

	videoMapByID := make(map[string]crcVideoMap, len(src.VideoMaps))
	for _, vm := range src.VideoMaps {
		if vm.ID == "" {
			continue
		}
		videoMapByID[vm.ID] = vm
	}

	referenced := make(map[string]struct{})
	for _, gm := range src.Facility.ERAMConfiguration.GeoMaps {
		dst.GeoMaps = append(dst.GeoMaps, copyERAMGeoMap(gm))
		for _, id := range gm.VideoMapIDs {
			if id == "" {
				return redsERAMMapPackage{}, fmt.Errorf("ERAM GeoMap %q references an empty video map id", gm.Name)
			}
			referenced[id] = struct{}{}
		}
	}

	ids := make([]string, 0, len(referenced))
	for id := range referenced {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	for _, id := range ids {
		meta, ok := videoMapByID[id]
		if !ok {
			return redsERAMMapPackage{}, fmt.Errorf("ERAM GeoMap references unknown video map %q", id)
		}

		geoJSONPath := filepath.Join(root, "VideoMaps", artcc, id+".geojson")
		geoJSON, err := os.ReadFile(geoJSONPath)
		if err != nil {
			return redsERAMMapPackage{}, fmt.Errorf("read ERAM videomap %s: %w", id, err)
		}

		geoJSON = bytes.TrimPrefix(geoJSON, []byte{0xEF, 0xBB, 0xBF})
		if !json.Valid(geoJSON) {
			return redsERAMMapPackage{}, fmt.Errorf("invalid GeoJSON in %s", geoJSONPath)
		}

		dst.VideoMaps = append(dst.VideoMaps, redsERAMVideoMap{
			ID:      id,
			Name:    meta.Name,
			TDMOnly: meta.TDMOnly,
			GeoJSON: json.RawMessage(geoJSON),
		})
	}

	return dst, nil
}

func copyERAMGeoMap(src crcERAMGeoMap) redsERAMGeoMap {
	dst := redsERAMGeoMap{
		Name:        src.Name,
		LabelLine1:  src.LabelLine1,
		LabelLine2:  src.LabelLine2,
		BCGMenu:     append([]string(nil), src.BCGMenu...),
		VideoMapIDs: append([]string(nil), src.VideoMapIDs...),
		FilterMenu:  make([]redsMapFilter, len(src.FilterMenu)),
	}

	for i, fm := range src.FilterMenu {
		dst.FilterMenu[i] = redsMapFilter{
			LabelLine1: fm.LabelLine1,
			LabelLine2: fm.LabelLine2,
		}
	}

	return dst
}

func atlasIsBinary(atlas []byte) bool {
	for _, value := range atlas {
		if value != 0 && value != 255 {
			return false
		}
	}
	return true
}

func glyphBitmapRows(fs legacyFontSize, glyph legacyGlyph) []uint32 {
	if glyph.width <= 0 || glyph.height <= 0 {
		return nil
	}

	width := int(glyph.width)
	height := int(glyph.height)
	atlasWidth := int(fs.atlasWidth)
	x0 := int(glyph.textureOffset)

	rows := make([]uint32, height)
	for y := 0; y < height; y++ {
		rowStart := y*atlasWidth + x0
		var row uint32
		for x := 0; x < width; x++ {
			if fs.atlasR8[rowStart+x] != 0 {
				row |= uint32(1) << uint(31-x)
			}
		}
		rows[y] = row
	}

	return rows
}

func glyphName(codepoint int32) string {
	if codepoint >= 0 && codepoint <= 0xffff {
		return fmt.Sprintf("uni%04X", codepoint)
	}
	return fmt.Sprintf("uni%06X", codepoint)
}

var eramWantedCursorNames = map[string]bool{
	"Eram1":                true,
	"Eram2":                true,
	"Eram3":                true,
	"Eram4":                true,
	"Eram5":                true,
	"EramDeletion":         true,
	"EramInvalidEnter":     true,
	"EramInvalidSelect":    true,
	"EramInvalidSelection": true,
}

var eramWantedCursorOrder = []string{
	"Eram1",
	"Eram2",
	"Eram3",
	"Eram4",
	"Eram5",
	"EramDeletion",
	"EramInvalidEnter",
	"EramInvalidSelect",
	"EramInvalidSelection",
}

func runEramCursors(args []string) error {
	fs := flag.NewFlagSet("eram cursors", flag.ContinueOnError)

	inPath := fs.String("in", "", "input CRC Cursors directory or one ERAM .cur/.cur.zst cursor file")
	outPath := fs.String("out", "", "output generated Go file")

	if err := fs.Parse(args); err != nil {
		return err
	}
	if *inPath == "" || *outPath == "" {
		return fmt.Errorf("usage: crc2reds eram cursors -in /path/to/CRC/Cursors -out eram/assets/cursors.go")
	}

	return convertEramCursors(*inPath, *outPath)
}

func convertEramCursors(inPath, outPath string) error {
	paths, err := eramCursorInputFiles(inPath)
	if err != nil {
		return err
	}
	if len(paths) == 0 {
		return fmt.Errorf("no ERAM .cur or .cur.zst files found in %s", inPath)
	}

	cursors := make([]cursorBitmap, 0, len(paths))
	seen := make(map[string]bool, len(paths))

	for _, path := range paths {
		cursor, err := decodeCursorFile(path)
		if err != nil {
			return err
		}
		if seen[cursor.name] {
			return fmt.Errorf("duplicate ERAM cursor name after sanitizing: %s", cursor.name)
		}
		seen[cursor.name] = true
		cursors = append(cursors, cursor)
	}

	sort.Slice(cursors, func(i, j int) bool {
		return eramCursorSortKey(cursors[i].name) < eramCursorSortKey(cursors[j].name)
	})

	if err := writeEramCursorGo(outPath, cursors); err != nil {
		return err
	}

	fmt.Printf("wrote %s\n", outPath)
	fmt.Print("converted ERAM cursors:")
	for _, cursor := range cursors {
		fmt.Printf(" %s(%dx%d hot=%d,%d)", cursor.name, cursor.width, cursor.height, cursor.hotspot[0], cursor.hotspot[1])
	}
	fmt.Println()

	return nil
}

func eramCursorInputFiles(inPath string) ([]string, error) {
	info, err := os.Stat(inPath)
	if err != nil {
		return nil, err
	}

	if !info.IsDir() {
		if !isCursorInputFile(filepath.Base(inPath)) {
			return nil, fmt.Errorf("-in must be an ERAM .cur/.cur.zst file or CRC's Cursors directory: %s", inPath)
		}
		return []string{inPath}, nil
	}

	entries, err := os.ReadDir(inPath)
	if err != nil {
		return nil, err
	}

	byName := make(map[string]string)
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		name := entry.Name()
		if strings.HasPrefix(name, "._") || !isCursorInputFile(name) {
			continue
		}

		cursorName := cursorNameFromPath(name)
		if !eramWantedCursorNames[cursorName] {
			continue
		}

		byName[cursorName] = filepath.Join(inPath, name)
	}

	paths := make([]string, 0, len(byName))
	missing := make([]string, 0)
	for _, name := range eramWantedCursorOrder {
		path, ok := byName[name]
		if !ok {
			missing = append(missing, name+".cur")
			continue
		}
		paths = append(paths, path)
	}

	if len(paths) == 0 {
		return nil, nil
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("ERAM cursor directory %s is missing expected CRC cursor files: %s", inPath, strings.Join(missing, ", "))
	}

	return paths, nil
}

func eramCursorSortKey(name string) int {
	for i, wanted := range eramWantedCursorOrder {
		if name == wanted {
			return i
		}
	}
	return len(eramWantedCursorOrder)
}

func writeEramCursorGo(outPath string, cursors []cursorBitmap) error {
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by cmd/crc2reds; DO NOT EDIT.\n")
	b.WriteString("// Source: ERAM .cur(.zst) files converted to exact RGBA cursor pixels.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", eramAssetPackage)
	fmt.Fprintf(&b, "import renderer %q\n\n", eramRendererImport)

	fmt.Fprintf(&b, "var %s = map[string]*renderer.CursorBitmap{\n", eramCursorVarName)

	for _, cursor := range cursors {
		fmt.Fprintf(&b, "\t%q: {\n", cursor.name)
		fmt.Fprintf(&b, "\t\tName:    %q,\n", cursor.name)
		fmt.Fprintf(&b, "\t\tWidth:   %d,\n", cursor.width)
		fmt.Fprintf(&b, "\t\tHeight:  %d,\n", cursor.height)
		fmt.Fprintf(&b, "\t\tHotspot: [2]int{%d, %d},\n", cursor.hotspot[0], cursor.hotspot[1])
		fmt.Fprintf(&b, "\t\tPixels:  %s,\n", formatUint32Array(cursor.pixels, "\t\t"))
		b.WriteString("\t},\n\n")
	}

	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "func %s(name string) (*renderer.CursorBitmap, bool) {\n", eramCursorFuncName)
	fmt.Fprintf(&b, "\tc, ok := %s[name]\n", eramCursorVarName)
	b.WriteString("\treturn c, ok\n")
	b.WriteString("}\n")

	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}
