package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	eramAssetPackage   = "assets"
	eramRendererImport = "github.com/juliusplatzer/reds/renderer"
	eramAllFontsVar    = "EramFonts"
)

type eramFamilyFonts struct {
	family string
	sizes  []legacyFontSize
}

func runEram(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: crc2reds eram <font> ...")
	}

	switch args[0] {
	case "font":
		return runEramFont(args[1:])
	default:
		return fmt.Errorf("unknown ERAM conversion %q; expected font", args[0])
	}
}

func runEramFont(args []string) error {
	fs := flag.NewFlagSet("eram font", flag.ContinueOnError)

	inPath := fs.String("in", "", "input ERAM .bin/.bin.zst font file or directory containing font files")
	outPath := fs.String("out", "", "output generated Go file")

	if err := fs.Parse(args); err != nil {
		return err
	}
	if *inPath == "" || *outPath == "" {
		return fmt.Errorf("usage: crc2reds eram font -in /path/to/eram-fonts-or-font.bin.zst -out eram/assets/font.go")
	}

	return convertEramFont(*inPath, *outPath)
}

func convertEramFont(inPath, outPath string) error {
	families, err := parseEramInputPath(inPath)
	if err != nil {
		return err
	}
	if len(families) == 0 {
		return fmt.Errorf("no .bin or .bin.zst font files found in %s", inPath)
	}

	if err := writeEramFontGo(outPath, families); err != nil {
		return err
	}

	fmt.Printf("wrote %s\n", outPath)
	fmt.Print("converted font families:")
	for _, family := range families {
		fmt.Printf(" %s(", family.family)
		for i, size := range family.sizes {
			if i > 0 {
				fmt.Print(",")
			}
			fmt.Print(size.size)
		}
		fmt.Print(")")
	}
	fmt.Println()

	return nil
}

func parseEramInputPath(inPath string) ([]eramFamilyFonts, error) {
	paths, err := eramInputFiles(inPath)
	if err != nil {
		return nil, err
	}

	families := make([]eramFamilyFonts, 0, len(paths))
	for _, path := range paths {
		raw, err := readMaybeZstd(path)
		if err != nil {
			return nil, err
		}

		family := fontFamilyFromPath(path)
		sizes, err := parseLegacyFont(family, raw)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		if err := validateEramFontSizes(sizes); err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}

		families = append(families, eramFamilyFonts{
			family: family,
			sizes:  sizes,
		})
	}

	sort.Slice(families, func(i, j int) bool {
		return families[i].family < families[j].family
	})
	return families, nil
}

func eramInputFiles(inPath string) ([]string, error) {
	info, err := os.Stat(inPath)
	if err != nil {
		return nil, err
	}
	if !info.IsDir() {
		if !isBinInputFile(filepath.Base(inPath)) {
			return nil, fmt.Errorf("-in must be an ERAM .bin/.bin.zst font file or a directory containing font files: %s", inPath)
		}
		return []string{inPath}, nil
	}

	entries, err := os.ReadDir(inPath)
	if err != nil {
		return nil, err
	}

	var paths []string
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasPrefix(name, "._") {
			continue
		}
		if isBinInputFile(name) {
			paths = append(paths, filepath.Join(inPath, name))
		}
	}
	sort.Strings(paths)
	return paths, nil
}

func validateEramFontSizes(sizes []legacyFontSize) error {
	for _, fs := range sizes {
		if !atlasIsBinary(fs.atlasR8) {
			return fmt.Errorf("font %s size %d is not binary 0/255; use alpha conversion instead", fs.family, fs.size)
		}

		for _, glyph := range fs.glyphs {
			if glyph.width > 32 {
				return fmt.Errorf("glyph too wide for VICE-style uint32 rows in size %d, codepoint %d: width=%d",
					fs.size, glyph.codepoint, glyph.width)
			}
		}
	}
	return nil
}

func writeEramFontGo(outPath string, families []eramFamilyFonts) error {
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by cmd/crc2reds; DO NOT EDIT.\n")
	b.WriteString("// Source: ERAM binary .bin(.zst) fonts converted to VICE-style 1-bit glyph rows.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", eramAssetPackage)
	fmt.Fprintf(&b, "import renderer %q\n\n", eramRendererImport)

	fmt.Fprintf(&b, "var %s = map[string]*renderer.MonoBitmapFont{\n", eramAllFontsVar)

	for _, family := range families {
		for _, fs := range family.sizes {
			writeEramFontLiteral(&b, fs)
		}
	}

	b.WriteString("}\n\n")

	for _, family := range families {
		varName := exportedFamilyVarName(family.family)
		fmt.Fprintf(&b, "var %s = map[int]*renderer.MonoBitmapFont{\n", varName)
		for _, fs := range family.sizes {
			fmt.Fprintf(&b, "\t%d: %s[%q],\n", fs.size, eramAllFontsVar, fontKey(fs))
		}
		b.WriteString("}\n\n")
	}

	for _, family := range families {
		funcName := exportedFamilyFuncName(family.family)
		varName := exportedFamilyVarName(family.family)
		fmt.Fprintf(&b, "func %s(size int) (*renderer.MonoBitmapFont, bool) {\n", funcName)
		fmt.Fprintf(&b, "\tf, ok := %s[size]\n", varName)
		b.WriteString("\treturn f, ok\n")
		b.WriteString("}\n\n")
	}

	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}

func writeEramFontLiteral(b *strings.Builder, fs legacyFontSize) {
	fmt.Fprintf(b, "\t%q: {\n", fontKey(fs))
	fmt.Fprintf(b, "\t\tPointSize: %d,\n", fs.size)
	fmt.Fprintf(b, "\t\tWidth:     %d,\n", nominalWidth(fs))
	fmt.Fprintf(b, "\t\tHeight:    %d,\n", fs.lineHeight)
	b.WriteString("\t\tGlyphs: []renderer.MonoBitmapGlyph{\n")

	for _, glyph := range fs.glyphs {
		bitmapRows := glyphBitmapRows(fs, glyph)
		offsetX := glyph.bearingX
		offsetY := fs.lineHeight - glyph.bearingY

		fmt.Fprintf(b, "\t\t\t%d: {\n", glyph.codepoint)
		fmt.Fprintf(b, "\t\t\t\tName:   %q,\n", glyphName(glyph.codepoint))
		fmt.Fprintf(b, "\t\t\t\tStepX:  %d,\n", glyph.advance)
		fmt.Fprintf(b, "\t\t\t\tBounds: [2]int{%d, %d},\n", glyph.width, glyph.height)
		fmt.Fprintf(b, "\t\t\t\tOffset: [2]int{%d, %d},\n", offsetX, offsetY)
		fmt.Fprintf(b, "\t\t\t\tBitmap: %s,\n", formatUint32Array(bitmapRows, "\t\t\t\t"))
		b.WriteString("\t\t\t},\n")
	}

	b.WriteString("\t\t},\n")
	b.WriteString("\t},\n\n")
}

func fontKey(fs legacyFontSize) string {
	return fmt.Sprintf("%s-%d", fs.family, fs.size)
}

func fontFamilyFromPath(path string) string {
	base := filepath.Base(path)
	base = strings.TrimSuffix(base, ".zst")
	base = strings.TrimSuffix(base, ".bin")
	return sanitizeIdent(base)
}

func exportedFamilyVarName(family string) string {
	return sanitizeIdent(family) + "Fonts"
}

func exportedFamilyFuncName(family string) string {
	return sanitizeIdent(family) + "Font"
}

func atlasIsBinary(atlas []byte) bool {
	for _, value := range atlas {
		if value != 0 && value != 255 {
			return false
		}
	}
	return true
}

func glyphBitmapRows(fs legacyFontSize, glyph legacyGlyph) []uint32 {
	if glyph.width <= 0 || glyph.height <= 0 {
		return nil
	}

	width := int(glyph.width)
	height := int(glyph.height)
	atlasWidth := int(fs.atlasWidth)
	x0 := int(glyph.textureOffset)

	rows := make([]uint32, height)
	for y := 0; y < height; y++ {
		rowStart := y*atlasWidth + x0
		var row uint32
		for x := 0; x < width; x++ {
			if fs.atlasR8[rowStart+x] != 0 {
				row |= uint32(1) << uint(31-x)
			}
		}
		rows[y] = row
	}

	return rows
}

func glyphName(codepoint int32) string {
	if codepoint >= 0 && codepoint <= 0xffff {
		return fmt.Sprintf("uni%04X", codepoint)
	}
	return fmt.Sprintf("uni%06X", codepoint)
}
