package radar

import (
	"errors"
	"fmt"
	"sync"

	"github.com/juliusplatzer/reds/util"
)

const magneticVariationTilesResource = "resources/nav/tiles.json.zst"

var errMagneticVariationTilesUnavailable = errors.New("magnetic variation tile resource unavailable")

var loadMagneticVariationTiles = sync.OnceValues(func() (*MagneticVariationTileSet, error) {
	if !util.ResourceExists(magneticVariationTilesResource) {
		return nil, errMagneticVariationTilesUnavailable
	}
	r := util.LoadResource(magneticVariationTilesResource)
	defer r.Close()
	return DecodeMagneticVariationTileSet(r)
})

// MagneticVariationAt returns the STARS magnetic variation in degrees,
// positive west. Within the generated adaptation domain this is deliberately
// piecewise constant: the value comes from the magnetic-variation tile that
// contains the supplied display center. That mirrors the behavior described
// by FAA JO 6191.3 more closely than a single facility-wide WMM value.
//
// The bundled tiles are an approximation generated by cmd/wmm2reds, not the
// FAA/OSF site-adaptation tile listing. Outside the generated tile domain (or
// when developing without the generated resource) REDS falls back to the
// bilinearly interpolated WMM field.
func MagneticVariationAt(lat, lon float64) (float64, error) {
	tiles, err := loadMagneticVariationTiles()
	if err == nil {
		if variation, ok := tiles.Lookup(lat, lon); ok {
			return variation, nil
		}
	} else if !errors.Is(err, errMagneticVariationTilesUnavailable) {
		return 0, fmt.Errorf("load magnetic variation tiles: %w", err)
	}

	return WMMVariationAt(lat, lon)
}
