package radar

import (
	"errors"
	"fmt"
	"sync"

	"github.com/juliusplatzer/reds/util"
)

const magneticVariationTilesResource = "resources/nav/tiles.json.zst"

var errMagneticVariationTilesUnavailable = errors.New("magnetic variation tile resource unavailable")

var loadMagneticVariationTiles = sync.OnceValues(func() (*MagneticVariationTileSet, error) {
	if !util.ResourceExists(magneticVariationTilesResource) {
		return nil, errMagneticVariationTilesUnavailable
	}
	r := util.LoadResource(magneticVariationTilesResource)
	defer r.Close()
	return DecodeMagneticVariationTileSet(r)
})

// MagneticVariationAt returns the STARS magnetic variation in degrees,
// positive west. The value is deliberately piecewise constant: it comes from
// the magnetic-variation tile that contains the supplied display center.
//
// The bundled tiles are an approximation generated by cmd/wmm2reds, not the
// FAA/OSF site-adaptation tile listing. The generated tile set is the sole
// runtime magnetic-adaptation source; the WMM grid used to generate it is a
// build/development input and is not consulted by REDS at runtime.
func MagneticVariationAt(lat, lon float64) (float64, error) {
	tiles, err := loadMagneticVariationTiles()
	if err != nil {
		return 0, fmt.Errorf("load magnetic variation tiles: %w", err)
	}
	if variation, ok := tiles.Lookup(lat, lon); ok {
		return variation, nil
	}
	return 0, fmt.Errorf(
		"magnetic variation point %.6f, %.6f outside tile-set bounds [%.6f, %.6f] x [%.6f, %.6f]",
		lat, lon,
		tiles.Bounds.South, tiles.Bounds.North,
		tiles.Bounds.West, tiles.Bounds.East,
	)
}
